# Assignment 1, 8-Puzzle Programming

### Your homework must be implemented in this Notebook file. 
### You can add as many cells as you want. However, you are not allowed to touch the code below the line "=============".
### You need to implement the three (four for grads) searching functions and the print result functions.
### For the searching functions, feel free to customize the return data types and parameter lists as long as the function name is as required.


In [9]:
import numpy as np
import time
GOAL_STATE = [0,1,2,3,4,5,6,7,8]

In [10]:
class Node:
    def __init__(self,state,parent,level):
        self.state = state
        self.parent = parent
        self.level = level

In [11]:
def find_blank_tile(state):
    zero_index = [i for i in np.where(state==0)]
    return zero_index[0]

def find_possible_moves(node,visited):
    #print(" In find possible moves with state: ",node.state)
    next_possible_moves = []
    state = node.state
    
    #try moving tile left
    if is_legal_move(state = state,move='W'):
        state_left = try_move(state,move='W')
        if not is_state_visited(state_left,visited):
            new_left_node = Node(state = state_left, parent = node,level = node.level+1)
            #node.children.append(new_left_node)
            next_possible_moves.append(new_left_node)
            #print("state left added : ",state_left)                  
    
    #try moving tile up
    if is_legal_move(state=state,move ='N'):
        state_up = try_move(state,move='N')
        if not is_state_visited(state_up,visited):
            new_up_node = Node(state = state_up,parent = node,level =node.level+1)
            #node.children.append(new_up_node)
            next_possible_moves.append(new_up_node)
            #print("state up added : ",state_up)
    
    #try moving tile down
    if is_legal_move(state= state,move='S'):
        state_down = try_move(state,move='S')
        if not is_state_visited(state_down,visited):
            new_down_node = Node(state = state_down,parent =node,level =node.level+1)
            #node.children.append(new_down_node)
            next_possible_moves.append(new_down_node)
            #print("state down added : ",state_down)
                
    #try moving tile right
    if is_legal_move(state=state,move='E'):
        state_right = try_move(state,move='E')
        if not is_state_visited(state_right,visited):
            new_right_node = Node(state = state_right, parent = node,level = node.level+1)
            #node.children.append(new_right_node)
            next_possible_moves.append(new_right_node)
            #print("state right added : ",state_right)
          
    return next_possible_moves

def is_goal_state(state):
    goal = np.array(GOAL_STATE,dtype= np.int8)
    #if((state == goal).all()):
    if(np.array_equal(goal,state)):
        return True
    else:
        return False

def is_legal_move(state,move):
    zero_index = find_blank_tile(state)
    index = zero_index[0]
    if move =='E':
        if index % 3 == 2: #Invalid right move
            return False    
    elif move=='W':
        if index%3 ==0: #Invalid left move
            return False
    elif move == 'N': #Invalid move up
        if index<3:
            return False 
    elif move == 'S':  # Invalid move down
        if index > 5:
            return False
    
    return True

# def is_state_visited(state,visited):
#     return next((True for element in visited if element is state),False)
def is_state_visited(state,visited):
    if hash(tuple(state)) in visited:
        return True
    else:
        return False
       
def is_state_explored(state,explored):
    return next((True for element in explored if element is state),False)

def swap(state,ind1,ind2):
        temp = state[ind1]
        state[ind1] = state[ind2]
        state[ind2] = temp
        return state
    
def try_move(state,move):
    index = find_blank_tile(state)
    next_state = np.copy(state)
    if move == 'N':
        new_state = swap(next_state,index,index-3)
    
    elif move == 'S':
        new_state = swap(next_state,index,index+3)
        
    elif move == 'E': 
        next_state = swap(next_state,index,index+1)
            
    elif move == 'W':
        next_state = swap(next_state,index,index-1)
            
    else:
        return None
        
    return next_state

In [12]:
#implementation of function "Iterative_deepening_DFS"
#Pseudocode:
#IDS pseudocode:
#   depth = 0
#while True:
#   result = depth-limited-search(d)
#   if result == goal
#       return result
#   else
#       depth = depth +1

def iterative_DFS(node,index):
    depth =0
    #print("AT depth: ",depth)
    while True:
        result = depth_limited_search(node = node,limit = depth)
        if result != None:
            if is_goal_state(result.state):
                step_count = print_result_IDDFS(node =result,index=index)
                return step_count
        else:
            depth = depth +1
            
# Psuedo-code
#Depth-limited-search(limit)
#   stack.push(initialState)
#       while not done:
#          node=pop()
#       if goalTest(node):
#          return node
#       else:
#           if depth(node) < limit:
#              children = successor-fn(node)
#               for child in children
#                   push(child)
#           else:
#              return None

def depth_limited_search(node,limit):
    #print("**************In depth limited search with limit: ", limit," ***********")
    if limit <0:
        return False
    state = node.state
    frontier = [node] #stack implementation
    visited = set()
    explored = set()
    while frontier:
        curr_node = frontier.pop()
        curr_state = curr_node.state
        #print("New State poped: ", curr_state)
        visited.add(hash(tuple(curr_state)))
        if(is_goal_state(curr_state)):
            #print("yahoooo found it!!")
            return curr_node
        else:
            if curr_node.level <limit:
                next_possible_moves = find_possible_moves(curr_node,visited)
                for move in next_possible_moves:
                    if not hash(tuple(move.state)) in explored:
                        frontier.append(move)
                    explored.add(hash(tuple(curr_state)))
                #print_values(frontier)
                           
            else:
                continue

def print_result_IDDFS(node,index):
    state_tracker = [node.state]
    count = 1
    while node.parent:
        node =node.parent
        state_tracker.append(node.state)
        count = count+1
    
    if index == 1:
        print("Moves to reach solution via IDDFS:")
        
        print(np.array(state_tracker.pop()).reshape(3,3))
        while state_tracker:
            print('to')
            print(np.array(state_tracker.pop()).reshape(3,3))
    return count


In [13]:
#implementation of function "breadthFirstSearch" (for graduate students)
#Psuedocode:
# def BFS:
#   queue.enqueue(initialState)
#   while not done:
#       node = queue.dequeue()
#       if goalTest(node):
#           return node
#       else:
#           children = find-succcessor-moves(node)
#           for every move:
#               queue.enqueue(move)

def breadthFirstSerach(node,index):
    state = node.state
    #print(node.state)
    frontier = [node]#queue to store unvisited states
    visited = set() # to keep track of visited states
    explored = set()#to keep track of states explored but not yet visited

    while frontier:
        curr_node = frontier.pop(0)
        curr_state = curr_node.state
        
        visited.add(hash(tuple(curr_state)))
        
        if(is_goal_state(curr_state)):
            step_count = print_result_BFS(node =curr_node,index = index)
            return step_count
        else:
            next_possible_moves = find_possible_moves(curr_node,visited)
            for move in next_possible_moves:
                if not hash(tuple(move.state)) in explored:
                    frontier.append(move)
                explored.add(hash(tuple(move.state)))
                
def print_result_BFS(node,index):
    #print("index ", index)
    state_tracker = [node.state]
    count = 1
    while node.parent:
        node =node.parent
        state_tracker.append(node.state)
        count = count +1
    if index == 1:    
        print("Moves to reach solution via BFS:")   
        print(np.array(state_tracker.pop()).reshape(3,3))
        while state_tracker:
            print('to')
            print(np.array(state_tracker.pop()).reshape(3,3))
    return count

In [14]:
def read_input_file():
    file = open("Input8PuzzleCases.txt","r")
    inputlist=[]
    index =0
    for line in file:
        #print(line)
        newline = line.strip("\n").split(",")
        inputlist.append(np.array(newline,dtype=np.int8))
        #test_input_file(line = inputlist[index])
        index+=1        
    file.close()
    return inputlist

In [15]:
#implementation of function "print_result(result)"
def print_result(result):
    inputlist =read_input_file()
    
    #Solution using IDDFS
    ids_time_list = []
    ids_stepcount_list = []
    lineNum = 1 #used to print only first solution
    for i in range (100):
        start_time = time.time()
        line = np.array(inputlist[i],dtype= np.int8)
        root_node = Node(state = line,parent = None,level = 0)
        step_count = iterative_DFS(root_node,index =lineNum)
        end_time = time.time()
        ids_time_list.append(end_time-start_time)
        ids_stepcount_list.append(step_count)
        lineNum = lineNum+1
    
    #Solution using BFS
    bfs_time_list = []
    bfs_stepcount_list = []
    index =1
    for i in range (20):
        start_time = time.time()
        line = np.array(inputlist[i],dtype= np.int8)
        root_node = Node(state = line,parent = None,level = 0)
        step_count = breadthFirstSerach(root_node,index =index)
        end_time = time.time()
        bfs_time_list.append(end_time-start_time)
        bfs_stepcount_list.append(step_count)
        index = index+1
        
        
    #Print analysis results
    print('\t\t\t Average_Time \t\t Average_Steps')
    print('\t IDS \t\t ', sum(ids_time_list)/100, ' \t \t', sum(ids_stepcount_list)/100)
    print('\t BFS \t\t ', sum(bfs_time_list)/20, ' \t \t', sum(bfs_stepcount_list)/20)



In [17]:
if __name__ == "__main__":
    print_result(None)

Moves to reach solution via IDDFS:
[[8 7 5]
 [4 1 2]
 [3 0 6]]
to
[[8 7 5]
 [4 1 2]
 [3 6 0]]
to
[[8 7 5]
 [4 1 0]
 [3 6 2]]
to
[[8 7 0]
 [4 1 5]
 [3 6 2]]
to
[[8 0 7]
 [4 1 5]
 [3 6 2]]
to
[[8 1 7]
 [4 0 5]
 [3 6 2]]
to
[[8 1 7]
 [4 5 0]
 [3 6 2]]
to
[[8 1 7]
 [4 5 2]
 [3 6 0]]
to
[[8 1 7]
 [4 5 2]
 [3 0 6]]
to
[[8 1 7]
 [4 5 2]
 [0 3 6]]
to
[[8 1 7]
 [0 5 2]
 [4 3 6]]
to
[[0 1 7]
 [8 5 2]
 [4 3 6]]
to
[[1 0 7]
 [8 5 2]
 [4 3 6]]
to
[[1 5 7]
 [8 0 2]
 [4 3 6]]
to
[[1 5 7]
 [8 3 2]
 [4 0 6]]
to
[[1 5 7]
 [8 3 2]
 [0 4 6]]
to
[[1 5 7]
 [0 3 2]
 [8 4 6]]
to
[[1 5 7]
 [3 0 2]
 [8 4 6]]
to
[[1 5 7]
 [3 2 0]
 [8 4 6]]
to
[[1 5 0]
 [3 2 7]
 [8 4 6]]
to
[[1 0 5]
 [3 2 7]
 [8 4 6]]
to
[[1 2 5]
 [3 0 7]
 [8 4 6]]
to
[[1 2 5]
 [3 7 0]
 [8 4 6]]
to
[[1 2 5]
 [3 7 6]
 [8 4 0]]
to
[[1 2 5]
 [3 7 6]
 [8 0 4]]
to
[[1 2 5]
 [3 7 6]
 [0 8 4]]
to
[[1 2 5]
 [0 7 6]
 [3 8 4]]
to
[[1 2 5]
 [7 0 6]
 [3 8 4]]
to
[[1 2 5]
 [7 6 0]
 [3 8 4]]
to
[[1 2 5]
 [7 6 4]
 [3 8 0]]
to
[[1 2 5]
 [7 6 4]
 [3 0 8]]
to
[[1 

You can insert as many cells as you want above
You are not Allowed to modify the code below this line.
===============================

In [ ]:
#you need to implement print_result function to print out the result according to the required format
print_result(result)


# The output format should be as follows. You only need to give one sample solution as an example.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Solution of the first Scenario:
#### X X X
#### X X X
#### X X X
#### to
#### X X X
#### X X X
#### X X X
#### to
#### X X X
#### X X X
#### X X X
#### to
#### X X X
#### X X X
#### X X X
#### to
#### .
#### .
#### .
#### 0 1 2
#### 3 4 5
#### 6 7 8

                Average_Steps    Average_Time      
 IDS
 
 BFS

